name: Go Build

on:
  watch:
    types: [started]
  schedule:
    - cron: "45 * * * *"
  workflow_dispatch:
    inputs:
      total_requests:
        description: 'Total number of requests'
        required: false
        default: '100000'
      concurrency:
        description: 'Number of concurrent workers'
        required: false
        default: '1000'
      test_mode:
        description: 'Test mode (normal/hangup)'
        required: false
        default: 'hangup'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure Origin
      uses: Boostport/setup-cloudflare-warp@v1
      with: 
        organization: ${{ secrets.CLOUDFLARE_ORGANIZATION }}
        auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run test
      run: |
        go mod tidy
        go run my.go
      timeout-minutes: 60

