name: Go Build

on:
  watch:
    types: [started]
  schedule:
    - cron: "45 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure Origin
      uses: Boostport/setup-cloudflare-warp@v1
      with: 
        organization: ${{ secrets.CLOUDFLARE_ORGANIZATION }}
        auth_client_id: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_ID }}
        auth_client_secret: ${{ secrets.CLOUDFLARE_AUTH_CLIENT_SECRET }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Run test
      run: |
        go mod tidy
        go run my.go
      timeout-minutes: 60

